using Content.Client.UserInterface.Controls;
using Content.Shared._Art.Market;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Art.Market.UI;

[GenerateTypedNameReferences]
public sealed partial class MarketRequestMenu : FancyWindow
{
    public Action<int>? OnBuyListing;

    private List<MarketListingData> _listings = new();
    private int _selectedIdx = -1;

    public MarketRequestMenu()
    {
        RobustXamlLoader.Load(this);

        ListingsList.OnItemSelected += args =>
        {
            _selectedIdx = args.ItemIndex;
            if (_selectedIdx < 0 || _selectedIdx >= _listings.Count) return;
            var l = _listings[_selectedIdx];
            SellerLabel.Text = l.SellerName;
            PriceLabel.Text = $"{l.Price} sp";
            ContentsList.Clear();
            foreach (var (name, count) in l.Contents)
                ContentsList.AddItem($"{name} x{count}");
        };

        ListingsList.OnItemDeselected += _ =>
        {
            _selectedIdx = -1;
            SellerLabel.Text = "-";
            PriceLabel.Text = "-";
            ContentsList.Clear();
        };

        BuyButton.OnPressed += _ =>
        {
            if (_selectedIdx >= 0 && _selectedIdx < _listings.Count)
                OnBuyListing?.Invoke(_listings[_selectedIdx].Id);
        };
    }

    public void Populate(List<MarketListingData> listings)
    {
        _listings = listings;
        _selectedIdx = -1;
        ListingsList.Clear();
        ContentsList.Clear();
        SellerLabel.Text = "-";
        PriceLabel.Text = "-";
        foreach (var l in listings)
            ListingsList.AddItem($"{l.LotName} | {l.SellerName} | {l.Price} sp");
    }
}