using Content.Client.UserInterface.Controls;
using Content.Shared._Art.Market;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Art.Market.UI;

[GenerateTypedNameReferences]
public sealed partial class MarketSaleMenu : FancyWindow
{
    public Action<string, int>? OnCreateListing;
    public Action<int>? OnCancelListing;

    private List<MarketListingData> _activeListings = new();
    private int _selectedListingIdx = -1;

    public MarketSaleMenu()
    {
        RobustXamlLoader.Load(this);

        PriceSpinBox.InitDefaultButtons();
        PriceSpinBox.IsValid = v => v >= 1;
        LotNameEdit.IsValid = s => s.Length <= 25;
        ActiveListingsList.OnItemSelected += args =>
        {
            _selectedListingIdx = args.ItemIndex;
        };
        ActiveListingsList.OnItemDeselected += _ =>
        {
            _selectedListingIdx = -1;
        };

        ListButton.OnPressed += _ =>
        {
            var name = LotNameEdit.Text.Trim();
            var price = PriceSpinBox.Value;
            if (!string.IsNullOrWhiteSpace(name) && price > 0)
                OnCreateListing?.Invoke(name, price);
        };

        CancelButton.OnPressed += _ =>
        {
            if (_selectedListingIdx >= 0 && _selectedListingIdx < _activeListings.Count)
                OnCancelListing?.Invoke(_activeListings[_selectedListingIdx].Id);
        };
    }

    public void Populate(
        Dictionary<string, int> contents,
        List<MarketListingData> listings,
        int maxListings)
    {
        ContainerList.Clear();
        foreach (var (name, count) in contents)
            ContainerList.AddItem($"{name} x{count}");

        _activeListings = listings;
        _selectedListingIdx = -1;
        ActiveListingsList.Clear();
        ActiveListingsLabel.Text = $"Your Active Listings ({listings.Count}/{maxListings}):";
        foreach (var l in listings)
            ActiveListingsList.AddItem($"[{l.Id}] {l.LotName} — {l.Price} sp");
    }
}